### ISSUE TITLE
How to use callbacks?

### ISSUE THREAD

**Issue by colesnicov** [corporateshark/minilog#4]
Hello. In the `README.md` you have an instruction to use a callback:

```
minilog::LogCallback cb = { .userData = this };
cb.funcs[minilog::Log] = [](void* data, const char* msg) { reinterpret_cast<GameConsole*>(data)->Display(msg); };
cb.funcs[minilog::Warning] = [](void* data, const char* msg) { reinterpret_cast<GameConsole*>(data)->DisplayError(msg); };
cb.funcs[minilog::FatalError] = [](void* data, const char* msg) { reinterpret_cast<GameConsole*>(data)->DisplayError(msg); };
minilog::callbackAdd(cb);
```

 I didn't find **how to pass the `GameConsole` object to the logger?**

**Comment by corporateshark** [comment]
@colesnicov You can pass any pointer as the `userData` member field. When callback functions are called, they will get that user-provided pointer as their `data` argument.

**Comment by colesnicov** [comment]
Ooh, yes. Sorry, I didn't notice this:
```
minilog::LogCallback cb = { .userData = this };
```
This one: `{ .userData = this }`.

Shame on me! :D
