### ISSUE TITLE
How to set output date format?

### ISSUE THREAD

**Issue by colesnicov** [corporateshark/minilog#5]
Hello. Because I assume that my program will run on the PC 7 days a week, 24 hours a day, so I think it would be good to have the option to set the output data format.

For example, instead of this one

```
(MAIN):00:53:07.674 minilog: initializing ...
```
I'd rather see this one:
```
(MAIN):19.06.2024-00:53:07.674 minilog: initializing ...
```

I don't want to create another fork, so I'm wondering if you could modify it a bit, where it would be possible to **pass the data format during initialization?** :)

**Comment by corporateshark** [comment]
Added custom time stamps and a new example https://github.com/corporateshark/minilog/commit/ce7d5e41aa448d3c4fe02ca3f8d752fbfd21234d.

The output can be as follows:

```
(MainThread):2024.Jun.18-21:59:43.664   minilog: initializing ...
(MainThread):2024.Jun.18-21:59:43.664   minilog: log file: log_timestamps.txt
(MainThread):2024.Jun.18-21:59:43.665   testCustomTimeStamp()->New Time Stamp!
(MainThread):2024.Jun.18-21:59:43.665   testCustomTimeStamp()->Another Time Stamp!!!
(MainThread):2024.Jun.18-21:59:43.666   testCustomTimeStamp()-><-
(MainThread):2024.Jun.18-21:59:43.666   minilog: deinitializing...
```

You can now change time stamps to be anything you want by providing a custom time-stamp-writing function via `LogConfig::writeTimeStamp`.
